site_name: BIG documantation
site_author: a-kuznetsov
site_url: https://docs.imbig.ai
repo_url: https://github.com/a-kuz/big-docs
docs_dir: src
repo_name: GitHub
theme:
  name: material
  features:
    - content.tooltips
    - navigation.indexes
    - toc.follow

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
nav:
  - Home: "index.md"
  - Requests:
      - Messaging:
          - Client requests: "client-requests.md"
          - -New: "client-requests#new"
          - -Edit: "client-requests#edit"
          - -Delete: "client-requests#delete"
          - -Delivered: "client-requests#dlvrd"
          - -Read: "client-requests#read"
          - -Reaction: "client-requests#reaction"
      - Retrieve data:
          - Client data requests: "client-retrieve.md"
          - -Chat: "client-retrieve#chat"
          - -Chats: "client-retrieve#chats"
          - -Messages: "client-retrieve#messages"
          - -Profile: "client-retrieve#profile"
          - -Profiles: "client-retrieve#profiles"
      - REST API:
          - Contacts API: "contacts.md"
          - Chat manage API: "chat-manage.md"
          - Privacy API: "privacy.md"
          - Profile API: "profile.md"
          - Stories API: "stories.md"
          - Reactions API: "reactions.md"
          - Files (old) API: "files-requests.md"
          - Files (new) API: "files-mpu-requests.md"

  - Events:
      - Client events: "client-events.md"
      - Server events: "server-events.md"
  - Types:
      - Contacts: "types/contacts.md"
      - Chat: "types/chat.md"
      - Chat list: "types/chat-list.md"
      - Message: "types/message.md"
      - Reply: "types/reply-to.md"
      - Forwarder from: "types/forwarded-from.md"
      - Attachment: "types/attachment.md"
      - Video: "types/video.md"

  - Calls: "calls.md"
  - Guides:
      - Ping: "ping.md"
      - Grouping events by key: "guides/grouping-events-by-key.md"
      - Delivered and read marks: "guides/dlvrd-read-marks-rules.md"
      - Message edit/delete: "guides/message-edit-delete.md"
      - Examples: "examples.md"
  - HTTP and more:
      - Upload File: "upload"
      - TUS Upload: "tus-upload"
      - HTTP API: "http-api"
      - HTTP API files: "http-api-files"
      - Your network: "https://dev.iambig.ai/network"
plugins:
  - render_swagger:
      allow_arbitrary_locations: true
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.blocks.details
  - pymdownx.snippets:
      auto_append:
        - "types/attachment"
        - "types/message"
        - "types/chat"
        - "types/chat-list"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
